namespace CallOfDuty.Models
{
    public class Properties
    {
        public int recordLongestWinStreak { get; set; }
        public int recordXpInAMatch { get; set; }
        public double accuracy { get; set; }
        public int losses { get; set; }
        public int totalGamesPlayed { get; set; }
        public int score { get; set; }
        public double winLossRatio { get; set; }
        public int totalShots { get; set; }
        public int bestScoreXp { get; set; }
        public int gamesPlayed { get; set; }
        public int bestSquardKills { get; set; }
        public int bestSguardWave { get; set; }
        public int bestConfirmed { get; set; }
        public int deaths { get; set; }
        public int wins { get; set; }
        public int bestSquardCrates { get; set; }
        public double kdRatio { get; set; }
        public int bestAssists { get; set; }
        public int bestFieldgoals { get; set; }
        public int bestScore { get; set; }
        public int recordDeathsInAMatch { get; set; }
        public double scorePerGame { get; set; }
        public int bestSPM { get; set; }
        public int bestKillChains { get; set; }
        public int recordKillsInAMatch { get; set; }
        public int suicides { get; set; }
        public double wlRatio { get; set; }
        public int currentWinStreak { get; set; }
        public int bestMatchBonusXp { get; set; }
        public int bestMatchXp { get; set; }
        public int bestSguardWeaponLevel { get; set; }
        public int bestKD { get; set; }
        public int kills { get; set; }
        public int bestKillsAsInfected { get; set; }
        public int bestReturns { get; set; }
        public int bestStabs { get; set; }
        public int bestKillsAsSurvivor { get; set; }
        public int timePlayedTotal { get; set; }
        public int bestDestructions { get; set; }
        public int headshots { get; set; }
        public int bestRescues { get; set; }
        public int assists { get; set; }
        public int ties { get; set; }
        public int recordKillStreak { get; set; }
        public int bestPlants { get; set; }
        public int misses { get; set; }
        public int bestDamage { get; set; }
        public int bestSetbacks { get; set; }
        public int bestTouchdowns { get; set; }
        public double scorePerMinute { get; set; }
        public int bestDeaths { get; set; }
        public int bestMedalXp { get; set; }
        public int bestDefends { get; set; }
        public int bestSquardRevives { get; set; }
        public int bestKills { get; set; }
        public int bestDefuses { get; set; }
        public int bestCaptures { get; set; }
        public int hits { get; set; }
        public int bestKillStreak { get; set; }
        public int bestDenied { get; set; }
        public int timePlayed { get; set; }
        public int captures { get; set; }
        public int defends { get; set; }
        public int shots { get; set; }
        public int damage { get; set; }
        public int extraStat1 { get; set; }
        public int uses { get; set; }
        public int awardedCount { get; set; }
        public int downs { get; set; }
        public int topTwentyFive { get; set; }
        public int objTime { get; set; }
        public int topTen { get; set; }
        public int contracts { get; set; }
        public int revives { get; set; }
        public int topFive { get; set; }
        public int tokens { get; set; }
        public int cash { get; set; }
        public int classChanges { get; set; }
        public int highestAvgAltitude { get; set; }
        public int killsFromBehind { get; set; }
        public int lmgDeaths { get; set; }
        public int riotShieldDamageAbsorbed { get; set; }
        public int flashbangHits { get; set; }
        public int meleeKills { get; set; }
        public int tagsLargestBank { get; set; }
        public int shotgunKills { get; set; }
        public int sniperDeaths { get; set; }
        public int timeProne { get; set; }
        public int killstreakWhitePhosphorousKillsAssists { get; set; }
        public int shortestLife { get; set; }
        public int deathsFromBehind { get; set; }
        public int higherRankedKills { get; set; }
        public int mostAssists { get; set; }
        public int leastKills { get; set; }
        public int tagsDenied { get; set; }
        public int killstreakWheelsonKills { get; set; }
        public int sniperHeadshots { get; set; }
        public int killstreakJuggernautKills { get; set; }
        public int smokesUsed { get; set; }
        public int avengerKills { get; set; }
        public int decoyHits { get; set; }
        public int killstreakCarePackageUsed { get; set; }
        public int molotovKills { get; set; }
        public int gasHits { get; set; }
        public int comebackKills { get; set; }
        public int lmgHeadshots { get; set; }
        public int smgDeaths { get; set; }
        public int carrierKills { get; set; }
        public int deployableCoverUsed { get; set; }
        public int thermiteKills { get; set; }
        public int arKills { get; set; }
        public int c4Kills { get; set; }
        public int clutch { get; set; }
        public int survivorKills { get; set; }
        public int killstreakGunshipKills { get; set; }
        public int timeSpentAsPassenger { get; set; }
        public int returns { get; set; }
        public int smgHeadshots { get; set; }
        public int launcherDeaths { get; set; }
        public int oneShotOneKills { get; set; }
        public int ammoBoxUsed { get; set; }
        public int spawnSelectSquad { get; set; }
        public int weaponPickups { get; set; }
        public int pointBlankKills { get; set; }
        public int tagsCaptured { get; set; }
        public int killstreakGroundKills { get; set; }
        public int distanceTraveledInVehicle { get; set; }
        public int longestLife { get; set; }
        public int stunHits { get; set; }
        public int spawnSelectFlag { get; set; }
        public int shotgunHeadshots { get; set; }
        public int bombDefused { get; set; }
        public int snapshotHits { get; set; }
        public int noKillsWithDeath { get; set; }
        public int killstreakAUAVAssists { get; set; }
        public int killstreakPersonalUAVKills { get; set; }
        public int tacticalInsertionSpawns { get; set; }
        public int launcherKills { get; set; }
        public int spawnSelectVehicle { get; set; }
        public int mostKillsLeastDeaths { get; set; }
        public int mostKills { get; set; }
        public int timeSpentAsDriver { get; set; }
        public int bombDetonated { get; set; }
        public int arHeadshots { get; set; }
        public int timeOnPoint { get; set; }
        public int lmgKills { get; set; }
        public int killstreakUAVAssists { get; set; }
        public int carepackagesCaptured { get; set; }
        public int mostKillsLongestStreak { get; set; }
        public int killstreakCruiseMissileKills { get; set; }
        public int longestStreak { get; set; }
        public int destroyedKillstreaks { get; set; }
        public int hipfireKills { get; set; }
        public int stimDamageHealed { get; set; }
        public int skippedKillcams { get; set; }
        public int leastAssists { get; set; }
        public int mostMultikills { get; set; }
        public int highestRankedKills { get; set; }
        public int killstreakAirstrikeKills { get; set; }
        public int distanceTravelled { get; set; }
        public int killstreakKills { get; set; }
        public int semtexKills { get; set; }
        public int penetrationKills { get; set; }
        public int explosionsSurvived { get; set; }
        public int highestMultikill { get; set; }
        public int arDeaths { get; set; }
        public int longshotKills { get; set; }
        public int proximityMineKills { get; set; }
        public int tagsMegaBanked { get; set; }
        public int mostKillsMostHeadshots { get; set; }
        public int firstInfected { get; set; }
        public int killstreakCUAVAssists { get; set; }
        public int throwingKnifeKills { get; set; }
        public int executionKills { get; set; }
        public int lastSurvivor { get; set; }
        public int reconDroneMarks { get; set; }
        public int deadSilenceKills { get; set; }
        public int revengeKills { get; set; }
        public int infectedKills { get; set; }
        public int killEnemyTeam { get; set; }
        public int sniperKills { get; set; }
        public int killstreakCluserStrikeKills { get; set; }
        public int meleeDeaths { get; set; }
        public int timeWatchingKillcams { get; set; }
        public int killstreakTankKills { get; set; }
        public int noKillNoDeath { get; set; }
        public int shotgunDeaths { get; set; }
        public int killstreakChopperGunnerKills { get; set; }
        public int shotsFired { get; set; }
        public int stoppingPowerKills { get; set; }
        public int pistolPeaths { get; set; }
        public int killstreakShieldTurretKills { get; set; }
        public int timeCrouched { get; set; }
        public int noDeathsFromBehind { get; set; }
        public int bombPlanted { get; set; }
        public int setbacks { get; set; }
        public int smgKills { get; set; }
        public int claymoreKills { get; set; }
        public int kills10NoDeaths { get; set; }
        public int pistolHeadshots { get; set; }
        public int killstreakVTOLJetKills { get; set; }
        public int mostDeaths { get; set; }
        public int adsKills { get; set; }
        public int empDroneHits { get; set; }
        public int defenderKills { get; set; }
        public int launcherHeadshots { get; set; }
        public int timesSelectedAsSquadLeader { get; set; }
        public int killstreakAirKills { get; set; }
        public int assaults { get; set; }
        public int fragKills { get; set; }
        public int killstreakEmergencyAirdropUsed { get; set; }
        public int killstreakChopperSupportKills { get; set; }
        public int spawnSelectBase { get; set; }
        public int noKill10Deaths { get; set; }
        public int leastDeaths { get; set; }
        public int killstreakSentryGunKills { get; set; }
        public int longestTimeSpentOnWeapon { get; set; }
        public int lowerRankedKills { get; set; }
        public int trophySystemHits { get; set; }
        public int clutchRevives { get; set; }
        public int lowestAvgAltitude { get; set; }
        public int pickups { get; set; }
        public int pistolKills { get; set; }
        public int reloads { get; set; }
        public int plants { get; set; }
        public int defuses { get; set; }
        public int setBacks { get; set; }
        public int stabs { get; set; }
        public int infected { get; set; }
        public int time { get; set; }
        public int confirms { get; set; }
        public int denies { get; set; }
        public int misc1 { get; set; }
        public int misc2 { get; set; }
    }
}
